version: '3.8'
services:
  db:
    container_name: pg_hestia_home
    image: postgres
    restart: no
#    restart: unless-stopped
#    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_hestia_home
    image: dpage/pgadmin4
    restart: no
#    restart: unless-stopped
#    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"