version: '3.8'
services:
  db:
    container_name: pg_container_hestia_home
    image: postgres
#    restart: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_hestia_home
    image: dpage/pgadmin4
#    restart:
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5052:80"

  app:
    build:
      context: ..
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - pgadmin
